apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
  labels:
    app: was
spec:
  replicas: 3
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      serviceAccountName: petclinic-ksa
      containers:
      - name: was-container
        image: gcr.io/kdt1-finalproject/njs-was:was-930dd2bfab2e65537f8099a64afb766cfe54d6ac
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
        ports:
        - name: http
          containerPort: 8080
      
      - name: cloud-sql-proxy 
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.17.1
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "200m"
        args:
        - "--structured-logs"
        - "--port=3306"
        - "--private-ip" 
        - "kdt1-finalproject:asia-northeast3:njs-db"
