steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [  
      'build', 
      '-t', 'gcr.io/kdt1-finalproject/njs-web:web-$COMMIT_SHA',
      '-f', 'web/Dockerfile',
      'web'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/kdt1-finalproject/njs-web:web-$COMMIT_SHA'
    ]
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'web']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-northeast3'     
      - 'CLOUDSDK_CONTAINER_CLUSTER=njs-cluster'    

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 600s
