steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'container', 'clusters', 'get-credentials',
        'njs-cluster',
        '--region', 'asia-northeast3',
        '--project', 'kdt1-finalproject'
      ]

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', '.']
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-northeast3'
      - 'CLOUDSDK_CONTAINER_CLUSTER=njs-cluster'

timeout: 600s
