apiVersion: apps/v1
kind: Deployment
metadata:
  name: web 
  labels:
    app: web
spec:
  replicas: 0
  selector:
    matchLabels:
      app: web  
  template: 
    metadata:
      labels:
        app: web  
    spec:
      containers:
      - name: web-container  
        image: gcr.io/kdt1-finalproject/njs-web:web-0e1907749aa990a0405a5c904d55aea9032cf2c2
        ports:
        - containerPort: 80
