apiVersion: apps/v1
kind: Deployment
metadata:
  name: web 
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web  
  template: 
    metadata:
      labels:
        app: web  
    spec:
      containers:
      - name: web-container  
        image: gcr.io/kdt1-finalproject/njs-web:web-080f3440310a7c82f884dbcaca5e6446d34055b7
        ports:
        - containerPort: 80
