apiVersion: apps/v1
kind: Deployment
metadata:
  name: web 
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web  
  template: 
    metadata:
      labels:
        app: web  
    spec:
      containers:
      - name: web-container  
<<<<<<< HEAD
        image: gcr.io/kdt1-finalproject/njs-web:web-82e1e789c1285377010031679096dc9215eab243
=======
        image: gcr.io/kdt1-finalproject/njs-web:web-82e1e789c1285377010031679096dc9215eab243
        resources:
          requests:
            cpu: "20m"
          limits:
            cpu: "200m"
>>>>>>> d8228be (web-config)
        ports:
        - containerPort: 80
        volumeMounts:
        - name: apache-config
          mountPath: /etc/apache2/sites-available/000-default.conf
          subPath: 000-default.conf
    volumes:
    - name: apache-config
      configMap:
        name: apache-proxy-config
