apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-proxy-config
  namespace: default
data:
  000-default.conf: |
    <VirtualHost *:80>
        ProxyPreserveHost On
        ProxyPass / http://was:8080/
        ProxyPassReverse / http://was:8080/
    </VirtualHost>


